# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b019a00720e68edcd91728ec43cd355f56e2f56c7e48acd17e02e4aef217cafb79429e1964f409638e9f0384b070f082699c7ea5fdd3b0de3de6fc748d80798

test:
  secret_key_base: 57083ff798881bed7590333e84016b2894fb2b14df6c289967b6d11edaf3a3d24bea40c9a35b7a14893262c32dda8addcb64ea823e7f9e9656065e62fae5235d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
