# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad38b1dd8ae50b860d0025f0511668fc8272c757a9f0c470db89f5369994e70cf016ae8630aa3ec846d39b25ece239b3f4b94daf587b0b9a459fd4fadaf153e9

test:
  secret_key_base: 09a6441d4b10af3891b4eaded16da9f375fc8044da976fbc882d3cbc05713580bfa14506e934e18ce9eeced18eaccd237d7da29d2cefb7eff69360e7bf9c9031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
